### PR TITLE
Currency in IncomeTransaction and InvestmentPosition is aChildAggrega…

### PR DESCRIPTION
**Pull request by simeonmalchev**
…te, not an Element, according to OFX Spec.

### CODE REVIEW

**Comment by simeonmalchev** [comment]
wrong

**Review by stoicflame — APPROVED** [review]

**Comment by stoicflame** [comment]
I haven't yet built and published a version of the library that has this change. I expect I'll get that done in the next day or two.

**Comment by simeonmalchev** [comment]
No problem at all.

**Comment by stoicflame** [comment]
Included in release version `1.34`.

**Comment by simeonmalchev** [comment]
Thanks!

**Pull request merged**
