### PR TITLE
Update FourOhOneKBalance.java

### LINKED ISSUE #53: Handling of BALLIST in INV401KBAL seems wrong
It looks like the code should use `@ChildAggregate` instead of `@Element` in `FourOhOneKBalance.java`

### PR DESCRIPTION
**Pull request by maor11**
Fix #53

### CODE REVIEW

**Review by stoicflame — APPROVED** [review]

**Comment by stoicflame** [comment]
I had to push b6ef567 for this to build. Can you confirm that's the right change?

**Comment by maor11** [comment]
Sorry, I'm new to this.
Yes, this looks ok.

**Comment by maor11** [comment]
BTW - how can I know when a new version is planned to be released to Maven?

**Comment by stoicflame** [comment]
Version 1.28.

**Pull request merged**
