### PR TITLE
Multiple Banking Statement Support

### PR DESCRIPTION
**Pull request by ashgupta1489**
Updated to support multiple banking statement request in one OFX request.

### CODE REVIEW

**Comment by stoicflame** [comment]
The changes look good, but will you please refactor to use 2-space tabs so I can better see the changes?

**Comment by ashgupta1489** [comment]
@stoicflame 
Absolutely. I would update it soon.

**Comment by ashgupta1489** [comment]
I have updated with space changes. I hope I didn't mess up the formatting.

**Review by stoicflame — APPROVED** [review]

**Comment by stoicflame** [comment]
Version 1.12 is now released.

**Pull request merged**
